### ISSUE TITLE
[Feature] Hope add sorting function on branch condition node

### ISSUE THREAD

**Issue by syssam** [bytedance/flow-builder#19]
[Feature] Hope add sorting function on branch condition node

**Comment by lixiao1022** [comment]
> [Feature] Hope add sorting function on branch condition node

Try to upgrade version 1.4.0, set sortable true, condition nodes will can be dragged and sorted in branch

**Comment by syssam** [comment]
@lixiao1022 would you provide a API, the we can call the sort function by the button?
some cases don't wanna use draggable ui

**Comment by lixiao1022** [comment]
> @lixiao1022 would you provide a API, the we can call the sort function by the button? some cases don't wanna use draggable ui

Try to upgrade version 1.4.3, the hook **useSort** provided four functions to sort node

**Comment by lixiao1022** [comment]
> @lixiao1022 would you provide a API, the we can call the sort function by the button? some cases don't wanna use draggable ui

@syssam Try to upgrade version 1.4.3, the hook useSort provided four functions to sort node
