### ISSUE TITLE
可以做一个循环节点吗？？

### ISSUE THREAD

**Issue by 3drinkerlgtm3** [bytedance/flow-builder#28]

**Comment by lixiao1022** [comment]
之前也考虑过，但目前的这种交互不太好行成环……

**Comment by agkrid** [comment]
我们怎样才能回到前一个节点？ 如果不可能？ 我们可以分叉吗？

**Comment by lixiao1022** [comment]
@3drinkerlgtm3 @agkrid 是类似于这种效果吗？
<img width="802" alt="image" src="https://user-images.githubusercontent.com/20854336/199437689-32ac8e7a-bf46-4c4e-b470-c300bac02e8f.png">

**Comment by agkrid** [comment]
@lixiao1022 不，如下图所示，
![image](https://user-images.githubusercontent.com/63926970/199445532-fa955482-7aae-483f-9772-6da681f6e88f.png)
