### ISSUE TITLE
可以增加尖头引导么 当前都是实现如果把start和end去掉就不知道方向了 

### ISSUE THREAD

**Issue by 1213William** [bytedance/flow-builder#30]
对于流的样式是否能够支持外部二次定义 比如把当前的边框的实线增加一定的圆角 或者把实线变成可配置（部分场景可能需要dotted）...

**Comment by lixiao1022** [comment]
@1213William 可以试一下升级到 1.4.5 版本，增加了显示箭头和自定义箭头内容。线的实线/虚线等风格可以按需覆盖下全局类名的样式，不同节点类型也可以传自定义类名，感觉这样会更灵活一点

**Comment by 1213William** [comment]
好的谢谢 稍后升上去看下效果
