### ISSUE TITLE
Customize Branch

### ISSUE THREAD

**Issue by Thap1** [bytedance/flow-builder#33]
How to custom condition node in branch?
![image](https://user-images.githubusercontent.com/44131532/203542063-410f5436-7729-419b-9784-ae89ae7bbd9b.png)

**Comment by lixiao1022** [comment]
> How to custom condition node in branch? ![image](https://user-images.githubusercontent.com/44131532/203542063-410f5436-7729-419b-9784-ae89ae7bbd9b.png)

`addConditionIcon` in registerNodes, and you can set `showArrow` true  in FlowBuilder to show default arrows
