### ISSUE TITLE
Support for If Condition node with yes / no child

### ISSUE THREAD

**Issue by mohit67890** [bytedance/flow-builder#36]
Hi,

I wanted to implement a condition node with a parent and then two sub-nodes to it.
I have tried loop and branch nodes but they dont seem to fulfil the requirement.

Is it possible to add that kind of a node type?

**Comment by lixiao1022** [comment]
> Hi,
> 
> I wanted to implement a condition node with a parent and then two sub-nodes to it. I have tried loop and branch nodes but they dont seem to fulfil the requirement.
> 
> Is it possible to add that kind of a node type?

Maybe you can add a new branch node(with yes/no child) below the condition node. You can change the name and the data about any condition nodes.

**Comment by mohit67890** [comment]
Hi,

I dont think its working like that.
What I need is a displayComponent for the Branch Node.

Also, I'm unable to create branch node below a condition node.

**Comment by lixiao1022** [comment]
> Hi,
> 
> I dont think its working like that. What I need is a displayComponent for the Branch Node.
> 
> Also, I'm unable to create branch node below a condition node.

You can try to set showPracticalBranchNode and showPracticalBranchRemove in registerNodes
{
    type: 'branch',
    name: 'Branch Node',
    conditionNodeType: 'condition',
    displayComponent: BranchNodeDisplay,
    showPracticalBranchNode: true,
    showPracticalBranchRemove: true,
  }

**Comment by mohit67890** [comment]
Thanks a lot..
**showPracticalBranchNode: true,** was the change required.
This is a very strong library. Great Work
