### ISSUE TITLE
Scroll workflow by mouse drag 

### ISSUE THREAD

**Issue by justyna363** [bytedance/flow-builder#38]
Is there any possibility to add scrolling by drag to FlowBuilder component ? It is one of missing element here.

**Comment by lixiao1022** [comment]
> Is there any possibility to add scrolling by drag to FlowBuilder component ? It is one of missing element here.

I will add an auto scrolling ability when dragging out of the FlowBuilder area.

**Comment by lixiao1022** [comment]
It seems that auto scroll is needed when dragover in '.flow-builder-content' element 🤔

**Comment by sunkid1995** [comment]
i had the same problem, but i solved it by

1. get element
const panElement = document.getElementsByClassName('flow-builder-content')[0];
2. handle mouse drag
panElement.style.cursor = 'grab';

      let pos = { top: 0, left: 0, x: 0, y: 0 };

      const mouseDownHandler = (event) => {
        panElement.style.cursor = 'grabbing';
        panElement.style.userSelect = 'none';

        pos = {
          left: panElement.scrollLeft,
          top: panElement.scrollTop,
          // Get the current mouse position
          x: event.clientX,
          y: event.clientY,
        };

        document.addEventListener('mousemove', mouseMoveHandler);
        document.addEventListener('mouseup', mouseUpHandler);
      };

      const mouseMoveHandler = (event) => {
        // How far the mouse has been moved
        const dx = event.clientX - pos.x;
        const dy = event.clientY - pos.y;

        // Scroll the element
        panElement.scrollTop = pos.top - dy;
        panElement.scrollLeft = pos.left - dx;
      };

      const mouseUpHandler = () => {
        panElement.style.cursor = 'grab';
        panElement.style.removeProperty('user-select');

        document.removeEventListener('mousemove', mouseMoveHandler);
        document.removeEventListener('mouseup', mouseUpHandler);
      };

      // Attach the handler
      panElement.addEventListener('mousedown', mouseDownHandler);

**Comment by lixiao1022** [comment]
Please try to upgrade to 2.6.0 version, and set scrollByDrag true
