### ISSUE TITLE
zoom缩放

### ISSUE THREAD

**Issue by Hello-job** [bytedance/flow-builder#39]
使用zoom缩放 在节点中加入一些antd的 popover组件 ，然后进行缩放会导致 位置错误

**Comment by Hello-job** [comment]
用transfrom: scale 缩放就没事

**Comment by Hello-job** [comment]
我这边使用 zoom使用 popover组件缩小的话 位置有问题 
但是自定义scalc就好了

**Comment by lixiao1022** [comment]
> 我这边使用 zoom使用 popover组件缩小的话 位置有问题 但是自定义scalc就好了

这个和 getPopupContainer 的设置有关。如果 getPopupContainer 是默认直接渲染到 body 上，用 scale 位置是正常的，但 popover 里面的内容其实没有被缩放；现在 sdk 里面 getPopupContainer 设置成挂在当前节点下，所以使用的 zoom，这样 popover 里面的内容也会被缩放的。你可以两种都试一下，看看哪个比较适用于你的场景
