### ISSUE TITLE
antd 依赖问题

### ISSUE THREAD

**Issue by zhangjuan01** [bytedance/flow-builder#4]
项目中必须引用了antd组件库才能使用
否则会报错
[https://fe.imdada.cn/uPic/U0AuqE.png](https://fe.imdada.cn/uPic/U0AuqE.png)

**Comment by csrigogogo** [comment]
https://codesandbox.io/s/9xzwl  官网示例里面 就是要引入antd

**Comment by csrigogogo** [comment]
![image](https://user-images.githubusercontent.com/74234437/154912665-38df7b18-d3a8-4d80-a996-7111c7fcc582.png)

**Comment by lixiao1022** [comment]
是的，用到了 antd 的几个组件，Popover、Popconfirm 这些

**Comment by WuJiY** [comment]
需要修改一些属性了  打开 visible 都换成open 了  会有warning

**Comment by lixiao1022** [comment]
> 需要修改一些属性了 打开 visible 都换成open 了 会有warning

感谢提醒，看到了 antd 4.23.0 之后会有这个警告
