### ISSUE TITLE
FlowBuilderInstance如何使用，希望能给一个使用demo

### ISSUE THREAD

**Issue by Theshy2019** [bytedance/flow-builder#45]

**Comment by lixiao1022** [comment]
http://react-flow-builder.site/#/zoom#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%A9%E6%94%BE%E5%B7%A5%E5%85%B7%E6%A0%8F 可以看看这个例子里面的代码，有 ref 的使用 demo
