### ISSUE TITLE
能否提供并行网关，支持会签的场景

### ISSUE THREAD

**Issue by lin-cq** [bytedance/flow-builder#46]
业务需要会签场景，发现当前貌似不能创建并行网关，能否支持一下？

**Comment by lixiao1022** [comment]
我们这边现在就是用分支节点来做并行网关的，你这边的交互上有什么特殊场景吗

**Comment by lin-cq** [comment]
> 比如一个任务，需要5个待审批人，其中任意两个审批通过就流转到下一个节点，activity标准流程那边是有个并行网关，我看咱们介绍里是没有的，想问问这种怎么实现的

**Comment by lixiao1022** [comment]
> > 比如一个任务，需要5个待审批人，其中任意两个审批通过就流转到下一个节点，activity标准流程那边是有个并行网关，我看咱们介绍里是没有的，想问问这种怎么实现的

对前端来说就是并行网关就是分支节点，主要还得看后端如何消费这个结构的数据
