### ISSUE TITLE
节点的高度必须是固定的？

### ISSUE THREAD

**Issue by Chang1ng** [bytedance/flow-builder#48]
<img width="674" alt="image" src="https://github.com/bytedance/flow-builder/assets/6593784/898489fb-4ff4-4cef-a6f8-1085e082b104">

**Comment by lixiao1022** [comment]
demo 里面的样式比较简单。实际用的话这个节点的展示内容可以通过 displayComponent 属性自定义，或者在默认的展示上进行一些样式调整

**Comment by lixiao1022** [comment]
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/6593784/251451685-898489fb-4ff4-4cef-a6f8-1085e082b104.png">

demo 里面的样式比较简单。实际用的话这个节点的展示内容可以通过 displayComponent 属性自定义，或者在默认的展示上进行一些样式调整
