### ISSUE TITLE
Zoom not working in Firefox (115.0.3)

### ISSUE THREAD

**Issue by gjoranm** [bytedance/flow-builder#49]
When using react-flow-builder v2 rendered in Firefox browser, the zoom feature does not work as expected.

When I click my custom zoom buttons or the internal FlowBuilder zoom buttons:

**Expected result:**
View is updated accordingly in all modern browsers

**Actual result:**
View is not changed after zoom value is changed when rendered in Firefox. Works as expected in Chrome.
Callback onZoomChange does however provide the expected resulting zoom value also in Firefox. So only the rendered view is not updated.

**My zoom handling code:**
```
  const builderRef = useRef<IFlowBuilderMethod>(null);

//Called from click event handler on custom zoom buttons. Also tested with setting zoom numerical value.
  const handleZoom = (zoomtype: ZoomType) => {
    builderRef.current!.zoom(zoomtype);
  };

//Provided as FlowBuilders onZoomChange callback. 
//This is called by FlowBuilder with the expected resulting value after zoom level change
  const handleZoomChange = (
    outDisabled: boolean,
    value: number,
    inDisabled: boolean
  ) => {
    setOutDisabled(outDisabled);
    setInDisabled(inDisabled);
    setZoom(value);
  };
        <FlowBuilder
          readonly
          ref={builderRef}
          nodes={nodes as INode[]}
          onZoomChange={handleZoomChange}
          zoomTool={{
            hidden: false, 
            min: 10,
            max: 150,
            step: 5,
          }}
          onChange={handleChange}
          registerNodes={registerNodes}
        />

  ```

**Comment by lixiao1022** [comment]
> When using react-flow-builder v2 rendered in Firefox browser, the zoom feature does not work as expected.
> 
> When I click my custom zoom buttons or the internal FlowBuilder zoom buttons:
> 
> **Expected result:** View is updated accordingly in all modern browsers
> 
> **Actual result:** View is not changed after zoom value is changed when rendered in Firefox. Works as expected in Chrome. Callback onZoomChange does however provide the expected resulting zoom value also in Firefox. So only the rendered view is not updated.
> 
> **My zoom handling code:**
> 
> ```
>   const builderRef = useRef<IFlowBuilderMethod>(null);
> 
> //Called from click event handler on custom zoom buttons. Also tested with setting zoom numerical value.
>   const handleZoom = (zoomtype: ZoomType) => {
>     builderRef.current!.zoom(zoomtype);
>   };
> 
> //Provided as FlowBuilders onZoomChange callback. 
> //This is called by FlowBuilder with the expected resulting value after zoom level change
>   const handleZoomChange = (
>     outDisabled: boolean,
>     value: number,
>     inDisabled: boolean
>   ) => {
>     setOutDisabled(outDisabled);
>     setInDisabled(inDisabled);
>     setZoom(value);
>   };
>         <FlowBuilder
>           readonly
>           ref={builderRef}
>           nodes={nodes as INode[]}
>           onZoomChange={handleZoomChange}
>           zoomTool={{
>             hidden: false, 
>             min: 10,
>             max: 150,
>             step: 5,
>           }}
>           onChange={handleChange}
>           registerNodes={registerNodes}
>         />
> ```

I see zoom property is no longer supported in Firefox~, but transform will make the position of Popover and Popconfirm abnormal. So recommend to use this feature in Chrome.
