### ISSUE TITLE
想问一下flow-builder后续的规划,有对应的路线图吗? 

### ISSUE THREAD

**Issue by csrigogogo** [bytedance/flow-builder#5]

**Comment by lixiao1022** [comment]
长久的暂时还没有 😅，最近在增加拖拽的能力，可以在手动点加号的地方放置

**Comment by WuJiY** [comment]
因为条件是有先后的，条件分支是否可以增加拖拽排序。

**Comment by lixiao1022** [comment]
> 因为条件是有先后的，条件分支是否可以增加拖拽排序。

确实会有这种场景，我看看怎么支持一下

**Comment by WuJiY** [comment]
> > 因为条件是有先后的，条件分支是否可以增加拖拽排序。
> 
> 确实会有这种场景，我看看怎么支持一下

有计划 条件类型 拖拽排序 添加进去吗

**Comment by lixiao1022** [comment]
> > > 因为条件是有先后的，条件分支是否可以增加拖拽排序。
> > 
> > 
> > 确实会有这种场景，我看看怎么支持一下
> 
> 有计划 条件类型 拖拽排序 添加进去吗

可以升级一下 1.4.0 版本，sortable 属性，条件节点可以在其所在分支内进行拖拽排序
