### ISSUE TITLE
子节点的数量可能不太对

### ISSUE THREAD

**Issue by howiekang** [bytedance/flow-builder#50]
![image](https://github.com/bytedance/flow-builder/assets/29764501/dd4dceb4-354e-417a-b40a-0b80653f318d)

这个名字是1的节点 ，children的内容是不是应该是空的才对。

**Comment by lixiao1022** [comment]
> ![image](https://user-images.githubusercontent.com/29764501/258630189-dd4dceb4-354e-417a-b40a-0b80653f318d.png)
> 
> 这个名字是1的节点 ，children的内容是不是应该是空的才对。

正常来说不应该有 children，是不是额外对数据进行了什么操作？ https://react-flow-builder.site/#/ 这个里面 demo 的 console.log 可以看到节点数据
