### ISSUE TITLE
registerNodes可以自定义样式吗

### ISSUE THREAD

**Issue by yhwtest** [bytedance/flow-builder#53]
比如我期望他可以是 一个jsx  然后onlcik注册增加节点的事件
![image](https://github.com/bytedance/flow-builder/assets/86184329/eec4fcb2-a14c-4a91-a4a1-9df9d34366ee)

**Comment by lixiao1022** [comment]
> 比如我期望他可以是 一个jsx 然后onlcik注册增加节点的事件 ![image](https://user-images.githubusercontent.com/86184329/262308670-eec4fcb2-a14c-4a91-a4a1-9df9d34366ee.png)

registerNodes 自定义样式是指点击加号的弹窗吗？addableComponent 属性可以进行自定义；另外提供了 hooks 进行增加节点 https://react-flow-builder.site/#/api#useaction

**Comment by yhwtest** [comment]
get 到啦~
