### ISSUE TITLE
How to get id of the deleted node

### ISSUE THREAD

**Issue by aayamdahal** [bytedance/flow-builder#54]
Hello I am having a problem to log the id of the node / branch i deleted. Any ideas?

**Comment by lixiao1022** [comment]
> Hello I am having a problem to log the id of the node / branch i deleted. Any ideas?

There is no way to get this id yet, should I add an prop onRemoveSuccess to get deleted node?

**Comment by aayamdahal** [comment]
yes please

**Comment by lixiao1022** [comment]
> yes please

please update to 2.2.0 version, try to use onRemoveNodeSuccess prop
