### ISSUE TITLE
Change `onAddNodeSuccess`  to return `INode`

### ISSUE THREAD

**Issue by fabricioloupias** [bytedance/flow-builder#58]
Is there any method to get only the aggregated node?
I see that there is the `onAddNodeSuccess` method but it only returns the `type`, it will be nice if it returns the entire node (`INode`)

**Comment by lixiao1022** [comment]
> Is there any method to get only the aggregated node? I see that there is the `onAddNodeSuccess` method but it only returns the `type`, it will be nice if it returns the entire node (`INode`)

please update to 2.3.0 version, and you can try to use the second param

**Comment by fabricioloupias** [comment]
> > Is there any method to get only the aggregated node? I see that there is the `onAddNodeSuccess` method but it only returns the `type`, it will be nice if it returns the entire node (`INode`)
> 
> please update to 2.3.0 version, and you can try to use the second param

It works perfect, thanks
