### ISSUE TITLE
Get only changed node

### ISSUE THREAD

**Issue by fabricioloupias** [bytedance/flow-builder#60]
It would be nice to detect any changes, to get only that node that was modified.

Currently `FlowBuilder.onChange()` shows all nodes,
Maybe it could be added as a parameter but only the modified node:

`onChange: (nodes: INode[], changeEvent?: string, nodeChanged: INode) => void`
The second parameter would have to be managed differently, perhaps with a default value, so that it does not break

Or add a new method to `FlowBuilder`: `onNodeChanged(nodeChanged: INode)`

**Comment by lixiao1022** [comment]
> It would be nice to detect any changes, to get only that node that was modified.
> 
> Currently `FlowBuilder.onChange()` shows all nodes, Maybe it could be added as a parameter but only the modified node:
> 
> `onChange: (nodes: INode[], changeEvent?: string, nodeChanged: INode) => void` The second parameter would have to be managed differently, perhaps with a default value, so that it does not break
> 
> Or add a new method to `FlowBuilder`: `onNodeChanged(nodeChanged: INode)`

Please try update to version **2.4.0**, added nodeChanged parameter.
