### ISSUE TITLE
[feature request] 能否增加画布拖动功能

### ISSUE THREAD

**Issue by africa1207** [bytedance/flow-builder#62]
目前节点和画布固定，同时画布高度固定时流程过多会出现滚动条，能否增加固定容器高度，使画布可拖动并使用鼠标滚轮缩放功能？

**Comment by lixiao1022** [comment]
> 目前节点和画布固定，同时画布高度固定时流程过多会出现滚动条，能否增加固定容器高度，使画布可拖动并使用鼠标滚轮缩放功能？

这种点击式交互的画布感觉还是滚动条合适一点，有空我研究一下增加拖动画布触发滚动的能力

**Comment by dllglishaoyi** [comment]
拖动画布功能 +10086

**Comment by maxis1718** [comment]
+1

**Comment by oswayne** [comment]
+1

**Comment by lixiao1022** [comment]
please try to upgrade 2.6.0 version, and set `scrollByDrag` true
