### ISSUE TITLE
可以支持在 FlowBuilder 里面支持传 children 吗，这样就可以share context 了

### ISSUE THREAD

**Issue by YuunYang** [bytedance/flow-builder#65]
如题，现在如果要使用到 builderContext 的状态，有什么好的办法嘛

**Comment by lixiao1022** [comment]
> 如题，现在如果要使用到 builderContext 的状态，有什么好的办法嘛

可以通过 ref 拿到，https://react-flow-builder.site/#/api#flowbuilderinstance
