### ISSUE TITLE
【特性】增加点击节点和点击画布的回调通知

### ISSUE THREAD

**Issue by entropy-cloud** [bytedance/flow-builder#68]
现在只有在配置了ConfigComponent的情况下才会通过onChange触发点击节点的回调通知。但是更灵活的界面组织需要在不使用内置的ConfigComponent机制的情况下也得到相应通知，然后动态选择如何处理，例如根据节点类型不同，动态选择drawer/dialog/property editor等编辑控件，显示位置也不同。
目前我在低代码平台NopPlatform中想集成FlowBuilder作为审批流的配置控件，我们会根据一个元模型配置动态生成前端的流程设计器，而不是在前端写死设计器的代码，所以需要更灵活的配置机制。希望能开放相关回调接口
https://github.com/entropy-cloud/nop-entropy

**Comment by lixiao1022** [comment]
> 现在只有在配置了ConfigComponent的情况下才会通过onChange触发点击节点的回调通知。但是更灵活的界面组织需要在不使用内置的ConfigComponent机制的情况下也得到相应通知，然后动态选择如何处理，例如根据节点类型不同，动态选择drawer/dialog/property editor等编辑控件，显示位置也不同。 目前我在低代码平台NopPlatform中想集成FlowBuilder作为审批流的配置控件，我们会根据一个元模型配置动态生成前端的流程设计器，而不是在前端写死设计器的代码，所以需要更灵活的配置机制。希望能开放相关回调接口 https://github.com/entropy-cloud/nop-entropy

听起来可以通过 displayComponent 自定义节点的点击行为，设置当前节点的选中状态
