### ISSUE TITLE
[Feature Request] 增加并行节点类型

### ISSUE THREAD

**Issue by oswayne** [bytedance/flow-builder#69]
目前的分支节点必须后置条件节点。并行分支应用场景还是比较多的，请问是否考虑增加并行节点类型。或者目前有什么实现方式？

**Comment by lixiao1022** [comment]
> 目前的分支节点必须后置条件节点。并行分支应用场景还是比较多的，请问是否考虑增加并行节点类型。或者目前有什么实现方式？

和并行节点的结构类似，但只是不需要条件节点对吧

**Comment by oswayne** [comment]
你好，感谢回复。
是的。并行结点之后不需要条件结点，可以多个分支同时进行而不是只能选择一个分支进行。多个分支同时进行会面临两种情况：多个分支独立和多个分支独立之后又聚合为一个分支。
可以参考一下 BPMN 的并行网关和聚合网关。

**Comment by lixiao1022** [comment]
> BPMN

如果结构类似的话，看是不是可以通过自定义【条件节点】的展示内容来达到相同的目的？因为目前的相互形式不支持多个独立分支，只区分包含分支的节点和不包含分支的节点，这种点击式的交互牺牲了一些灵活性。
