### ISSUE TITLE
buildFlatNodes 报错

### ISSUE THREAD

**Issue by zhaoo** [bytedance/flow-builder#7]
```
const handleChange = (nodes: INode[]) => {
    console.log('nodes change', nodes);
    setNodes(nodes);
    console.log(buildFlatNodes({ registerNodes, nodes }));
};
```

![image](https://user-images.githubusercontent.com/30286980/167081986-fd2e6e21-8389-40ea-9cf0-acd7da16d580.png)

**Comment by lixiao1022** [comment]
onChange 里面拿到的 nodes 数据中的 path 字段不准确，每次重新渲染才会计算一次 path，可以在 useEffect 里面调用这个方法
useEffect(() => { console.log(buildFlatNodes({ registerNodes, nodes })) }, [registerNodes , nodes]);

**Comment by zhaoo** [comment]
嗯嗯，我已经发现了哈，感谢~~

**Comment by lixiao1022** [comment]
> 嗯嗯，我已经发现了哈，感谢~~

在 1.0.1 版本中修复了这个报错（提前了 path 构建的操作，onChange 可以拿到准确的数据）
