### ISSUE TITLE
Cannot add data to the node with addNode

### ISSUE THREAD

**Issue by duongquoctai** [bytedance/flow-builder#74]
Hi, I am facing the issue that I cannot add data to the node with addNode function. Currently accept second parameter is a String type. Any idea to solve it? Thank you

**Comment by lixiao1022** [comment]
> Hi, I am facing the issue that I cannot add data to the node with addNode function. Currently accept second parameter is a String type. Any idea to solve it? Thank you

Please try to set `initializNodeData` in registerNodes.

**Comment by duongquoctai** [comment]
> > Hi, I am facing the issue that I cannot add data to the node with addNode function. Currently accept second parameter is a String type. Any idea to solve it? Thank you
> 
> Please try to set `initializNodeData` in registerNodes.

Can I update data when I use initializNodeData? I have multiple channels (such as Channel A, B, C ) and the data inside every channel node will update when user interact the form inside that node (The form will place inside displayComponent). Do you have any idea for that? Thank you very much

**Comment by lixiao1022** [comment]
> > > Hi, I am facing the issue that I cannot add data to the node with addNode function. Currently accept second parameter is a String type. Any idea to solve it? Thank you
> > 
> > 
> > Please try to set `initializNodeData` in registerNodes.
> 
> Can I update data when I use initializNodeData? I have multiple channels (such as Channel A, B, C ) and the data inside every channel node will update when user interact the form inside that node (The form will place inside displayComponent). Do you have any idea for that? Thank you very much

`initializNodeData` will only take effect once when adding nodes. Maybe you can find other sibling nodes based on `path` property, update their data, and `onChange([...nodes])`
