### ISSUE TITLE
Custom add button

### ISSUE THREAD

**Issue by brampurnot** [bytedance/flow-builder#83]
Is there a way to add a custom add button in between nodes that allows us to let the user choose a node type in a drawer or modal?

we don’t want to use the popover since we have too many node types hence I would like to see if we can customize this behavior. 

Bram

**Comment by lixiao1022** [comment]
> Is there a way to add a custom add button in between nodes that allows us to let the user choose a node type in a drawer or modal?
> 
> we don’t want to use the popover since we have too many node types hence I would like to see if we can customize this behavior.
> 
> Bram

This is not supported yet, maybe we can add a property to completely customize the behavior of the add button.

**Comment by brampurnot** [comment]
Thanks for the confirmation!
