### ISSUE TITLE
Custom button to open ConfigComponent inside DisplayComponent

### ISSUE THREAD

**Issue by fabricioloupias** [bytedance/flow-builder#87]
I was looking for a way for the drawer for the ConfigComponent to open from the click of a button inside the DisplayComponent.
Are there possibilities to disable the click in the entire DisplayComponent and generate a custom one within it?

The idea is to be able to have several buttons within the Display, the issue is that when you click anywhere in the Node, the ConfigComponent opens

**Comment by lixiao1022** [comment]
> I was looking for a way for the drawer for the ConfigComponent to open from the click of a button inside the DisplayComponent. Are there possibilities to disable the click in the entire DisplayComponent and generate a custom one within it?
> 
> The idea is to be able to have several buttons within the Display, the issue is that when you click anywhere in the Node, the ConfigComponent opens

You can disable opening the Drawer  in the entire DisplayComponent by `stopPropagation` in your DisplayComponent. And then call the `setSelectedNode` method in BuilderContext, so that you can customize the way to open the Drawer.

**Comment by fabricioloupias** [comment]
> > I was looking for a way for the drawer for the ConfigComponent to open from the click of a button inside the DisplayComponent. Are there possibilities to disable the click in the entire DisplayComponent and generate a custom one within it?
> > The idea is to be able to have several buttons within the Display, the issue is that when you click anywhere in the Node, the ConfigComponent opens
> 
> You can disable opening the Drawer in the entire DisplayComponent by `stopPropagation` in your DisplayComponent. And then call the `setSelectedNode` method in BuilderContext, so that you can customize the way to open the Drawer.
> 
> Here is a demo https://codesandbox.io/s/8wpqx7

Extraordinary, it was what I needed
Thank you!
